const AllData = [
    {
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    },
    {
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    },{
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    },{
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    },{
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    },{
        name:'16 Port Switch',
        model:'DS-1016',
        description:'16 Port Switch for Desktops',
        vendor:'D Link',
        serial_no:'FCS101GH69',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'24 port UPOE Switch',
        model:'9300-24UX',
        description:'24 port UPOE Switch',
        vendor:'Cisco',
        serial_no:'FCO2365GH5',
        category:'Network',
        status:'In-Stock',
        comment:'',
    },
    {
        name:'Gaming PC',
        model:'GameGen 12 PC',
        description:'Gaming PC',
        vendor:'ASUS',
        serial_no:'AO45KC3AF6',
        category:'System',
        status:'Checked-out',
        comment:'',
    }
]

export default AllData;